---
blank_issues_enabled: false
contact_links:
  - name: Gay Web Icons Discussions
    url: https://gh.gaywebicons.xyz/discussions
    about: Ask questions and share ideas related to the Gay Web Icons project here
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  # - name: Bug Report
  #   url: bug_report.yml
  #   about: Please report bugs here.
  # - name: New Icon Request
  #   url: new_icon_request.yml
  #   about: Use this form to request new icons.
  # - name: General Comments
  #   url: general.yml
  #   about: Please comment on anything you like here. Or you can <a href="https://gh.gaywebicons.xyz/discussions">open a discussion</a>.
