#
# feature_request.yml
#     Created: 2024-06-15T06:07:10-04:00
#    Modified: 2024-06-15T06:07:19-04:00
#      Author: David Gerard <david@iamtheantwink.com>
#   Copyright: © 2024 David Gerard, All Rights Reserved
#     License: MIT (https://opensource.org/licenses/MIT)
#

---
name: 🛠️ Feature Request
description: Suggest an idea to help us improve W&B
title: "[Feature]: "
labels:
  - "feature_request"
  - "triage"
  - "enhancement"
assignees:
  - iamtheantwink

body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this feature request report!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/GayWebIcons/GayWebIcons/issues?q=is%3Aissue+sort%3Acreated-desc+) for your feature.

        We are also happy to accept contributions from our users. For more details see [here](https://gaywebicons.xyz/CONTRIBUTING).

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g., email@example.com
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of the feature you're interested in.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Suggested Solution
      description: |
        Describe the solution you'd like. A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: |
        Describe alternatives you've considered.
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
    validations:
      required: false
